version: '3.7'

services:

  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - bot.env

  db:
    image: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - db.env

  panel:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_PORT=3306
      - PMA_HOST=db
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  # Database persistence
  db-data: